### ISSUE TITLE
storagepools_apis: creating storagepool with non-existing device returns 201

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#158]
### API
``POST /nodes/{nodeid}/storagepools```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25661807/5d99efac-3012-11e7-866d-283415142988.png)
 
**the storagepool was created**
![image](https://cloud.githubusercontent.com/assets/24386820/25661880/aa00f2dc-3012-11e7-8dca-a7c524f310a0.png)

### ays log
```
[Wed03 13:14] - Job.py              :54  :j.jobcontroller.job.def269e21f26b22631fc9c826f34cf7b - ERROR    - Traceback (most recent call last):
  File "/tmp/actions/storagepool/1d38b3321a4d20c4de36deed09ab9b8b.py", line 69, in install
    pool = node.storagepools.get(name)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 42, in get
    raise ValueError("Could not find StoragePool with name {}".format(name))
ValueError: Could not find StoragePool with name sp1

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storagepool/1d38b3321a4d20c4de36deed09ab9b8b.py", line 71, in install
    pool = node.storagepools.create(name, devices, metadataProfile, dataProfile, overwrite=True)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 50, in create
    device_names.append(part.devicename)
AttributeError: 'RuntimeError' object has no attribute 'devicename'
[Wed03 13:14] - RunStep.py          :88  :j.atyourservice                - INFO     - runstep 1: error
[Wed03 13:14] - Run.py              :107 :j.atyourservice                - ERROR    - error during execution of step 1 in run f7a5482e8ac88737b0544561b92e3060
Error of job: storagepool!sp1 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/tmp/actions/storagepool/1d38b3321a4d20c4de36deed09ab9b8b.py", line 69, in install
    pool = node.storagepools.get(name)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 42, in get
    raise ValueError("Could not find StoragePool with name {}".format(name))
ValueError: Could not find StoragePool with name sp1

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/storagepool/1d38b3321a4d20c4de36deed09ab9b8b.py", line 71, in install
    pool = node.storagepools.create(name, devices, metadataProfile, dataProfile, overwrite=True)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/StoragePool.py", line 50, in create
    device_names.append(part.devicename)
AttributeError: 'RuntimeError' object has no attribute 'devicename'
```

#SV
jumpscale 92c7a2d
grid faeae03b3

**Comment by ahmedelsayed-93** [comment]
### SV
js c8a4500
grid 67e7d28
