### ISSUE TITLE
vms_api: create vm returns error 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#227]
```
[Sun14 16:23] - RunStep.py          :84  :j.atyourservice                - INFO     - runstep 1: error
[Sun14 16:23] - Run.py              :108 :j.atyourservice                - ERROR    - error during execution of step 1 in run e0670dc9aefdad2a15c71e428c2df79e
Error of job: vm!vm (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/b7fe9c27c922d4a3932e0050552a56d6.py", line 375, in install
    kvm = get_domain(service)
  File "/tmp/actions/vm/b7fe9c27c922d4a3932e0050552a56d6.py", line 338, in get_domain
    for kvm in node.client.kvm.list():
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 1697, in list
    return self._client.json('kvm.list', {})
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 522, in json
    result = self.sync(command, arguments)
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 512, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"failed to list machines: virError(Code=1, Domain=7, Message='internal error: client socket is closed')"
)
```

**Comment by ahmedelsayed-93** [comment]
https://github.com/g8os/core0/issues/236

**Comment by john-kheir** [comment]
## Versions
Verified on 
core0-v: master c1513139664d3e782ddc72b8ea65c7376e11b19e
resourcepool-v: master  10a8901f3a26e9ee6275c322bf32307f4c2ed84f
