### ISSUE TITLE
vms_api: creating vm with boot vdisk returns error and stops ays server

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#230]
### create vdisk request

![image](https://cloud.githubusercontent.com/assets/24386820/26050843/84bae8dc-3960-11e7-9655-574cb688d5fb.png)

### create vm request
![image](https://cloud.githubusercontent.com/assets/24386820/26050809/6459281a-3960-11e7-806c-e1ede6f7ae2e.png)

### ays log
```
info
[Mon15 09:12] - bd210765f5df77bee57eb74d99a2c2b8.py:143 :j.jobcontroller.job.312153568186e4fdd6c303$
5d4d95449 - INFO     - create vm vm
[Mon15 09:12] - Job.py              :63  :j.jobcontroller.job.4c1b8bf4c2b4ebca10e72e9cf8fe8046 - IN$
O     - job job: bootstrap.g8os!grid1 (bootstrap) done sucessfuly
did not receive an Exceptio object for python exception, this is serious bug.
exceptionObject was:
[unknown key "iotune"] at -> //media/[0]/iotune
2017-05-15 09:12:48 - (sanic)[INFO]: Stopping worker [27096]
2017-05-15 09:12:48 - (sanic)[ERROR]: Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 450, in serve
    loop.run_forever()
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 393, in uvloop.loop.Loop._run (uvloop/loop.c:11845)
  File "uvloop/loop.pyx", line 295, in uvloop.loop.Loop._on_idle (uvloop/loop.c:10367)
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 49, in _execute_cb
    eco = j.errorconditionhandler.processPythonExceptionObject(ex)
  File "/opt/jumpscale8/lib/JumpScale/core/errorhandling/ErrorConditionHandler.py", line 126, in pr$
cessPythonExceptionObject
    exceptionObject=exceptionObject, tb=tb)
  File "/opt/jumpscale8/lib/JumpScale/core/errorhandling/ErrorConditionHandler.py", line 161, in pa$
sePythonExceptionObject
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 459, in serve
    loop.run_until_complete(http_server.wait_closed())
  File "uvloop/loop.pyx", line 1198, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25480)
  File "uvloop/loop.pyx", line 1191, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25324)
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 393, in uvloop.loop.Loop._run (uvloop/loop.c:11845)
  File "uvloop/loop.pyx", line 295, in uvloop.loop.Loop._on_idle (uvloop/loop.c:10367)
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "uvloop/future.pyx", line 448, in uvloop.loop.BaseTask._wakeup (uvloop/loop.c:114340)
  File "uvloop/future.pyx", line 441, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114043)
  File "uvloop/future.pyx", line 383, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:113654)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112669)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109361)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/bd210765f5df77bee57eb74d99a2c2b8.py", line 162, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/g8core/client.py", line 1434, in create
    self._create_chk.check(args)
  File "/usr/local/lib/python3.5/dist-packages/g8core/typchk.py", line 197, in check
    return self._check(self._typ, object, tracker)
  File "/usr/local/lib/python3.5/dist-packages/g8core/typchk.py", line 244, in _check
    self._check_dict(typ, object, t)
  File "/usr/local/lib/python3.5/dist-packages/g8core/typchk.py", line 212, in _check_dict
    self._check(attr_type, value, tx)
  File "/usr/local/lib/python3.5/dist-packages/g8core/typchk.py", line 236, in _check
    self._check_list(typ[0], object, t)
  File "/usr/local/lib/python3.5/dist-packages/g8core/typchk.py", line 202, in _check_list
    self._check(typ, elem, tx)
  File "/usr/local/lib/python3.5/dist-packages/g8core/typchk.py", line 244, in _check
    self._check_dict(typ, object, t)
  File "/usr/local/lib/python3.5/dist-packages/g8core/typchk.py", line 209, in _check_dict
    raise tx.reason('unknown key "{}"'.format(name))
g8core.typchk.Tracker: [unknown key "iotune"] at -> //media/[0]/iotune
did not receive an Exceptio object for python exception, this is serious bug.
exceptionObject was:
[unknown key "iotune"] at -> //media/[0]/iotune
**ERROR**
root@vm-74:/opt/code/github/jumpscale/jumpscale_core8/apps/atyourservice# 

```

### SV
js 507d2d0
resourcepool a3cc2bf

**Comment by ahmedelsayed-93** [comment]
###
js 507d2d0
resourcepool 81137e0
core0 56c40ef
